### ISSUE TITLE
Uncaught Error: selector must be a . delimted string eg (my.property)

### ISSUE THREAD

**Issue by NahidAhmed07** [barisates/react-data-table-component-extensions#40]
When I trying to export or print a document throw this error on console . 
Uncaught Error: selector must be a . delimted string eg (my.property)
    at getProperty (utilities.js:61:1)
    at utilities.js:106:1
    at Array.forEach (<anonymous>)
    at utilities.js:93:1
    at Array.forEach (<anonymous>)
    at Object.dataRender (utilities.js:91:1)
    at DataTableExtensions.onDataRender (index.js:116:1)
    at DataTableExtensions.onPrint (index.js:165:1)
    at Object.onClick (index.js:227:1)
    at onClick (ui.js:85:1)

**Comment by eddylackmann** [comment]
I Have the same Issue

**Comment by AbnerLR-iSoft** [comment]
I have to react-data-table-component version =  "^7.5.2" and "react-data-table-component-extensions": "^1.6.0"


This happened to me when i want to export, and i solved to problem like this 

columns = [
    { name: 'Folio', selector: row => row.Cfdi_Folio, cellExport: row => row.Cfdi_Folio, sortable: true },
    ...
]


You must have this format in selector (selector: row => row.title ) Add to cellExport if you want to export 

i followed to documentation 

https://www.npmjs.com/package/@innenpkg/react-data-table-component-extensions


![image](https://user-images.githubusercontent.com/79226673/177861038-01d4748b-cb9d-443f-bed5-5e607e806013.png)

**Comment by outboxtecnologia** [comment]
Hello @AbnerLR-iSoft 

can you give me an example of how to apply this property?

**Comment by davilatk** [comment]
I Have the same Issue

**Comment by SaqibJamil7866** [comment]
You have to define **cellExport** function in columns array.

const columns = [
  {
    id: "id",
    name: "ID",
    selector: (row) => row.id,
    cellExport: (row) => row.id,
    sortable: true,
  },
  {
    id: "title",
    name: "Title",
    selector: (row) => row.title,
    cellExport: (row) => row.title,
    sortable: true,
  },
  {
    id: "year",
    name: "Year",
    selector: (row) => row.year,
    cellExport: (row) => row.year,
    sortable: true,
  },
];
